added some usage info for 'docker-volume' script

diff --git a/files/docker-volume b/files/docker-volume
--- a/files/docker-volume
+++ b/files/docker-volume
@@ -1,9 +1,13 @@
 #!/usr/bin/env bash
 
 set -e
-echo -e "\nRun at $(date)"
 
-command="$1"
+command=$1
+commands=(
+  backup
+  restore
+  help
+)
 host_backup_dir=/tmp/container-data-backup
 container_backup_dir=/backup
 container_name="$2"
@@ -20,6 +24,13 @@ docker_args=(
   "$container_image"
 )
 
+help() {
+  echo -e "usage: $(basename "$0") <command> <container-name> <container-data-dirs>\n"
+  echo -e "example: $(basename "$0") backup my-container data/dir/1 data/dir/2"
+  printf "\tDo not use leading forward slashes when specifying container-data-dirs\n\n"
+  printf "commands:\n"
+  printf "\t%s\n" "${commands[@]}"
+}
 
 # backup files from a docker volume into a compressed archive
 backup() {
@@ -60,6 +71,12 @@ restore() {
   echo "Restored files:"
   docker "${docker_args[@]}" ls -lh "${@:2}"
 }
+
+if ! printf '%s\n' "${commands[@]}" | grep -q "^${command}$"; then
+  echo -e "Command $command not found\n"
+  help
+  exit 1
+fi
 
 mkdir -p $host_backup_dir
 "$command" "$container_name" "${container_data_dirs[@]}"
